ARG NODE_BASE_IMAGE=node:24.11.1
ARG NGINX_BASE_IMAGE=nginx:1.27

FROM ${NODE_BASE_IMAGE} AS frontend-builder

WORKDIR /app/spx-gui

COPY spx-gui/package.json spx-gui/package-lock.json .

ARG NPM_CONFIG_REGISTRY
RUN npm install --ignore-scripts

COPY spx-gui/account.html spx-gui/vite.config.account.ts spx-gui/vercel-output-plugin.ts .
COPY spx-gui/tsconfig.json spx-gui/tsconfig.app.json spx-gui/tsconfig.node.json .
COPY spx-gui/.env spx-gui/.env.production spx-gui/.env.staging .
COPY spx-gui/public ./public
COPY spx-gui/src ./src

ARG NODE_ENV=production
ENV NODE_OPTIONS=--max-old-space-size=4096
RUN NODE_ENV=${NODE_ENV} npx vite build --config vite.config.account.ts --mode ${NODE_ENV}

FROM ${NGINX_BASE_IMAGE}

COPY --from=frontend-builder /app/spx-gui/dist /usr/share/nginx/html
COPY spx-gui/nginx.account.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
